import Head from 'next/head'
import styles from './style.module.scss'

const Meta = () => {
  return (
    <Head>
      <title>Telegram Storage</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Meta
